### ISSUE TITLE
[Android Bootcamp] Group Project - Review Sprint #1

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#12]
PTAL at our 1st sprint. Any feedback is much appreciated.

/cc @nesquena @thecodepath

**Comment by nidhi1608** [comment]
Impressive work creating and distributing tasks for sprint 1. 
- Goals are well defined and seem achievable in the given timeframe.
- Impressed that you are already thinking about documenting overall strategy and most design decisions. 
- Depending on the strategy your group has come up with, consider creating regular check ins to sync up your code to avoid having multiple errors at the end.
-  Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Look forward to what you all come up with.
